// export const mockEvents = [
//   {
//     id: "1",
//     title: "Hacking Paris | GHRCE",
//     theme: "Innovation & Technology",
//     date: "Dec 15-17, 2024",
//     location: "Paris, France",
//     status: "Live" as const,
//     type: "Open" as const,
//     participants: 250,
//     tags: ["Bootcamp", "Web Dev"],
//     category: "Hackathon",
//   },
//   {
//     id: "2",
//     title: "HackMeet 1.0",
//     theme: "AI & Machine Learning",
//     date: "Jan 20-22, 2025",
//     location: "Mumbai, India",
//     status: "Offline" as const,
//     type: "Open" as const,
//     participants: 180,
//     tags: ["AI", "ML"],
//     category: "Hackathon",
//   },
//   {
//     id: "3",
//     title: "Sankalp 101",
//     theme: "Social Impact",
//     date: "Feb 5-7, 2025",
//     location: "Delhi, India",
//     status: "Online" as const,
//     type: "Open" as const,
//     participants: 320,
//     tags: ["Social", "Impact"],
//     category: "Hackathon",
//   },
//   {
//     id: "4",
//     title: "Girlathon",
//     theme: "Women in Tech",
//     date: "Mar 8-10, 2025",
//     location: "Bangalore, India",
//     status: "Offline" as const,
//     type: "Open" as const,
//     participants: 150,
//     tags: ["Women", "Tech"],
//     category: "Hackathon",
//   },
//   {
//     id: "5",
//     title: "HackArena",
//     theme: "Gaming & VR",
//     date: "Apr 12-14, 2025",
//     location: "Hyderabad, India",
//     status: "Online" as const,
//     type: "Open" as const,
//     participants: 200,
//     tags: ["Gaming", "VR"],
//     category: "Hackathon",
//   },
//   {
//     id: "6",
//     title: "Cultural Fest 2025",
//     theme: "Arts & Culture",
//     date: "May 1-3, 2025",
//     location: "Pune, India",
//     status: "Offline" as const,
//     type: "Open" as const,
//     participants: 500,
//     tags: ["Arts", "Culture"],
//     category: "Cultural",
//   },
//   {
//     id: "7",
//     title: "Sports Championship",
//     theme: "Athletics",
//     date: "Jun 15-17, 2025",
//     location: "Chennai, India",
//     status: "Offline" as const,
//     type: "Open" as const,
//     participants: 300,
//     tags: ["Sports", "Athletics"],
//     category: "Sports",
//   },
//   {
//     id: "8",
//     title: "React Workshop",
//     theme: "Frontend Development",
//     date: "Jul 20-21, 2025",
//     location: "Online",
//     status: "Online" as const,
//     type: "Open" as const,
//     participants: 100,
//     tags: ["React", "Frontend"],
//     category: "Workshop",
//   },
// ]
